---
output:
  word_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---
```{r, include=FALSE}
library(tidyverse)
library(tidymodels)
library(caret)
library(gridExtra)
library(vip)
library(ranger)
library(skimr)
```

```{r}
drug <- read_csv("~/Documents/School/Predictive Analytics/Module 4/Random Forests/drug_data-1.csv")
```

```{r}
names(drug) = c("ID", "Age", "Gender", "Education", "Country", "Ethnicity",
"Nscore", "Escore", "Oscore", "Ascore", "Cscore", "Impulsive",
"SS", "Alcohol", "Amphet", "Amyl", "Benzos", "Caff", "Cannabis",
"Choc", "Coke", "Crack", "Ecstasy", "Heroin", "Ketamine", "Legalh",
"LSD", "Meth", "Mushrooms", "Nicotine", "Semer", "VSA")
str(drug)
```

```{r}
drug[drug == "CL0"] = "No"
drug[drug == "CL1"] = "No"
drug[drug == "CL2"] = "Yes"
 drug[drug == "CL3"] = "Yes"
drug[drug == "CL4"] = "Yes"
 drug[drug == "CL5"] = "Yes"
drug[drug == "CL6"] = "Yes"
```

```{r}
drug_clean = drug %>% mutate_at(vars(Age:Ethnicity), funs(as_factor)) %>%
mutate(Age = factor(Age, labels = c("18_24", "25_34", "35_44",
"45_54", "55_64", "65_"))) %>%
mutate(Gender = factor(Gender, labels = c("Male", "Female"))) %>%
 mutate(Education = factor(Education, labels =
c("Under16", "At16", "At17", "At18", "SomeCollege",
"ProfessionalCert", "Bachelors", "Masters", "Doctorate"))) %>%
mutate(Country = factor(Country,
labels = c("USA", "NewZealand", "Other", "Australia",
"Ireland","Canada","UK"))) %>%
  mutate(Ethnicity = factor(Ethnicity,
 labels = c("Black", "Asian", "White", "White/Black", "Other",
"White/Asian", "Black/Asian"))) %>%
 mutate_at(vars(Alcohol:VSA), funs(as_factor)) %>%
select(-ID)
```

```{r}
str(drug_clean)
```

```{r}
drug_clean = drug_clean %>% select(!(Alcohol:Mushrooms)) %>% select(!(Semer:VSA))
names(drug_clean)
```

```{r}
skim(drug_clean)
###There does not appear to be missing data
```

```{r}
set.seed(1234)
drug_Clean_Split = initial_split(drug_clean, prob = 0.70, strata = Nicotine)
train = training(drug_Clean_Split)
test = testing(drug_Clean_Split)
```

```{r}
p1 = ggplot(drug_clean, aes(x = Age, fill = Nicotine)) + geom_bar(position = "fill")
p2 = ggplot(drug_clean, aes(x = Gender, fill = Nicotine)) + geom_bar(position = "fill")
p3 = ggplot(drug_clean, aes(x = Education, fill = Nicotine)) + geom_bar(position = "fill")
p4 = ggplot(drug_clean, aes(x = Country, fill = Nicotine)) + geom_bar(position = "fill")
grid.arrange(p1,p2,p3,p4)
```

```{r}
p1 = ggplot(drug_clean, aes(x = Ethnicity, fill = Nicotine)) + geom_bar(position = "fill")
p2 = ggplot(drug_clean, aes(x = Nicotine, y = Nscore)) + geom_boxplot()
p3 = ggplot(drug_clean, aes(x = Nicotine, y = Escore)) + geom_boxplot()
p4 = ggplot(drug_clean, aes(x = Nicotine, y = Oscore)) + geom_boxplot()

grid.arrange(p1,p2,p3,p4, ncol = 2)

```

```{r}
p1 = ggplot(drug_clean, aes(x = Nicotine, y = Ascore)) + geom_boxplot()
p2 = ggplot(drug_clean, aes(x = Nicotine, y = Cscore)) + geom_boxplot()
p3= ggplot(drug_clean, aes(x = Nicotine, y = Impulsive)) + geom_boxplot()
p4= ggplot(drug_clean, aes(x = Nicotine, y = SS)) + geom_boxplot()
grid.arrange(p1,p2,p3,p4, ncol = 2)

```

```{r}
###Age: With greater age less people are using Nicotine
###Gender: More Females use Nicotine than males
###Education doesnt have a large affect on Nicotine
###country doesnt have a large affect on Nicotine
###Ethnicity: some ethnicities have larger use of Nicotine but regardless of ethnicity there is use.
###Nscore,Escore,Oscore: all have use but lower Oscore have more use rather than a higher score. 
###Ascore,Cscore: both have use regardless of high or low scores
###Impulsive: Higher or way lower scores have use.
###SS: Hardly has nicotine use based on the score.
```

```{r}
set.seed(123)
rf_folds = vfold_cv(drug_clean, v = 5)
```

```{r}
drug_Clean_recipe2 = recipe(Nicotine ~., drug_clean) %>%
  step_dummy(all_nominal(), -all_outcomes())

rf_model = rand_forest(mtry = tune(), min_n = tune(), trees = 100) %>% 
  set_engine("ranger", importance = "permutation") %>% 
  set_mode("classification")

Nicotine_wflow = 
  workflow() %>% 
  add_model(rf_model) %>% 
  add_recipe(drug_Clean_recipe2)

rf_grid = grid_regular(
  mtry(range = c(2, 8)), 
  min_n(range = c(5, 20)), 
  levels = 10)

set.seed(123)
rf_res_tuned = tune_grid(
  Nicotine_wflow,
  resamples = rf_folds,
  grid = rf_grid )


```

```{r}
rf_res_tuned %>%
  collect_metrics() %>%
  filter(.metric == "accuracy") %>%
  select(mean, min_n, mtry) %>%
  pivot_longer(min_n:mtry,
    values_to = "value",
    names_to = "parameter"
  ) %>%
  ggplot(aes(value, mean, color = parameter)) +
  geom_point(show.legend = FALSE) +
  facet_wrap(~parameter, scales = "free_x") +
  labs(x = NULL, y = "Accuracy")
```

